server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/car_rental"
    username: 'root'
    password: 'password'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate