UPDATE cars SET status='AVAILABLE' WHERE status='ACTIVE';

ALTER TABLE clients ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE employees ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'EMPLOYED';
ALTER TABLE rentals ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED';
